### ISSUE TITLE
Radial axis display glitch

### ISSUE THREAD

**Issue by ZedLeb** [Microsoft/timelinestoryteller#140] opened 2018-06-12 11:47 UTC
What a fabulous visualisation - I really hope you have some support in developing further!

I have a glitch to add to the list :)

Upon first view of this scene the axis are not visible (I did wait a while).
Advancing to the next scene and then returning to the first scene gives the full view (see second screenshot)

![capture](https://user-images.githubusercontent.com/8373677/41288473-bf6aba90-6e46-11e8-80f8-7d11ac56cb98.PNG)

![capture 2](https://user-images.githubusercontent.com/8373677/41288540-fc0e1fe6-6e46-11e8-82fb-f6a2a10bb163.PNG)

**Comment by mattbrehmer** [comment] 2018-10-02 16:29
Duplicate of #71

**Closed by mattbrehmer** 2018-10-02 16:29 UTC
Labels: duplicate
